### PR TITLE
added modules, imported getter fn()s, assigned them to variables

### PR DESCRIPTION
**Pull request by yungreg**

### CODE REVIEW

**Review by AJWebDevel — APPROVED** [review]
looks good. --Approved

**Review by mqmanan — APPROVED** [review]
looks good ~~

**Review by Valerie-Freeman — APPROVED** [review]
Yo man looks great!

**Review by Vince4136 — APPROVED** [review]
Looks A Ok from my way

**Review by MorganEro — APPROVED** [review]
LOOKS GREAT

**Pull request merged**
